### ISSUE TITLE
automatic parameter validity checks

### ISSUE THREAD

**Issue by phigas** [anufrievroman/freepaths#14]
To improve the usability of the software certain parameters should be checked against the simulation after it finished.
For example if the pixel size is smaller than one step of a phonon it could give a warning.
Or if the timesteps are too short compared to the times the phonons need to travel through the structure.

Maybe there is even a way to give a clear measure of convergence.

**Comment by phigas** [comment]
Also a complete page on the wiki explaining the different config parameters and some context behind them would be very useful for new users

**Comment by anufrievroman** [comment]
Yes, there are some checks that happen in `config.py` before the simulation, but some useful feedback could be given after the simulation as well. By the way, I'll need to add some security check in the `config.py` to account for deprecated parameters and new parameters.

**Comment by anufrievroman** [comment]
I've added the post simulation parameter check to generate a few different warning, although I am not sure if too small pixels is really a problem.

**Comment by phigas** [comment]
I think we are already checking for the deprecated parameters. I added all those that i removed and some others i found.
Good job with the post simulation checks.
While having too small pixels is probably not too bad i think it's sill fine to keep the warning.

**Comment by anufrievroman** [comment]
Okay, I'll close this one for now. I'll address the convergence check in another error related issue.
