### ISSUE TITLE
Bug in parabola bottom

### ISSUE THREAD

**Issue by phigas** [anufrievroman/freepaths#22]
The collimating behaviour of the bottom parabola is incorrect. The scattering seems to be happening in the wrong direction.

![bottom focussing](https://github.com/anufrievroman/freepaths/assets/30627896/426b89d3-894f-4418-bd64-069d93d26e48)
![top collimating](https://github.com/anufrievroman/freepaths/assets/30627896/ddba40e3-1710-434e-b404-ae6655bdb7ba)
![top focussing](https://github.com/anufrievroman/freepaths/assets/30627896/c42957dd-bcdb-4f45-accd-aa7c5f708031)
![bottom collimating](https://github.com/anufrievroman/freepaths/assets/30627896/048d452e-c4b3-46bf-a69f-c75790283aa1)

**Comment by phigas** [comment]
The images with red lines through the structures are directional phonon sources. These are focussing cases. The other ones are collimating cases where the phonons are generated in the focus of the parabola

**Comment by anufrievroman** [comment]
I checked, yes, apparently the bottom parabola works when used to collimate (that's why we never noticed before) but fails when used to focus. In fact, the scattering code for top and bottom parabola is the same, which is probably wrong. I'll need to check it more seriously.

**Comment by anufrievroman** [comment]
Looks like I fixed it, although I didn't test extensively. 
![image](https://github.com/anufrievroman/freepaths/assets/42904990/77a845d5-9a0a-4de8-811b-68dfa01cbdde)
![image](https://github.com/anufrievroman/freepaths/assets/42904990/934a366f-d00c-4b19-b3f2-3ef209334340)
So, I'll close it for now.
